# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm
  - node.js
  - java
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
steps:
- task: NodeTool@0
  displayName: 'Install Node.js and Use Node 10.x'
  inputs:
    versionSpec: 10.x
    checkLatest: true
- task: CacheBeta@1
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: $(npm_config_cache)
    cacheHitVar: CACHE_RESTORED
- script: |
    pwd
    cd samples/jquery-cdn
    #npm install
  displayName: 'change directory'
- script: npm ci
  displayName: 'npm ci'
- task: Gulp@0
  displayName: 'Bundle project'
  inputs:
    targets: bundle
    arguments: '--ship'




